import {
  LayoutDashboard,
  ClipboardCheck,
  MessageSquare,
  BookOpenCheck,
  PlusCircle,
  Flag,
  Users,
  Megaphone,
  CheckCheck,
  Bell,
  BookOpen,
  FileEdit,
  ListChecks,
  AlertTriangle,
  BarChart3,
  Star,
  Inbox,
  Briefcase,
  CircleDot,
  Loader2,
  CircleCheck,
  Radio,
  Building2,
  Calendar,
  HelpCircle,
  Route,
  ClipboardList,
  Lightbulb,
  Mic,
  GraduationCap,
  FileText,
  Sparkles,
  ShieldCheck,
  TrendingUp,
  Layers,
  Send,
  UploadCloud,
  Image as ImageIcon,
  Paperclip,
  ArrowUp,
  ArrowRight,
  ArrowLeft,
  Search,
  Filter,
  Trash2,
  Pencil,
  Plus,
  X,
  Check,
  Eye,
  EyeOff,
  LogOut,
  ChevronRight,
  ChevronDown,
  Clock,
  Flame,
  Info,
  ThumbsUp,
  FileSpreadsheet,
  Zap,
  Target,
  Award,
  UserCircle,
  Home,
  MessageCircle,
  Frown,
  Angry,
  Meh,
  Smile,
  Laugh,
  type LucideIcon,
} from "lucide-react";

export type { LucideIcon };

export const Icon = {
  Dashboard: LayoutDashboard,
  Assessments: ClipboardCheck,
  Feedback: MessageSquare,
  Recovery: BookOpenCheck,
  RaiseIssue: PlusCircle,
  MyIssues: Flag,
  Flag,
  Community: Users,
  Evaluations: Megaphone,
  YouSaid: CheckCheck,
  Bell,
  Courses: BookOpen,
  MarkAssessment: FileEdit,
  Rubric: ListChecks,
  AtRisk: AlertTriangle,
  Analytics: BarChart3,
  Star,
  Inbox,
  Cases: Briefcase,
  New: CircleDot,
  InProgress: Loader2,
  Resolved: CircleCheck,
  StudentVoice: Radio,
  Departments: Building2,
  Calendar,
  Questions: HelpCircle,
  Routing: Route,
  Actions: ClipboardList,
  Insights: Lightbulb,
  Voice: Mic,
  Learning: GraduationCap,
  Reports: FileText,
  Ai: Sparkles,
  Shield: ShieldCheck,
  Trend: TrendingUp,
  Templates: Layers,
  Send,
  Upload: UploadCloud,
  Image: ImageIcon,
  Paperclip,
  ArrowUp,
  ArrowRight,
  ArrowLeft,
  Search,
  Filter,
  Trash: Trash2,
  Edit: Pencil,
  Plus,
  X,
  Check,
  Eye,
  EyeOff,
  LogOut,
  ChevronRight,
  ChevronDown,
  Clock,
  Flame,
  Info,
  ThumbsUp,
  Spreadsheet: FileSpreadsheet,
  Spark: Zap,
  Target,
  Award,
  User: UserCircle,
  Home,
  Chat: MessageCircle,
  Frown,
  Angry,
  Meh,
  Smile,
  Laugh,
};
